name: peace_pulse
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7 
  google_fonts: ^5.1.0 
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.0
  http: ^1.1.0  #used for the API call
  flutter_audio_waveforms: ^1.2.1+8       # for audio Visualization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/json/
  # fonts:
  # - assets/fonts/
